version: "3"
services:
  web:
    container_name: nginx
    image: nginx
    restart: always
    networks:
      - php_nginx_mysql 
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/www:/var/www
      - ./nginx/logs:/var/log/nginx
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
     - "80:80"
     - "443:443"

  php-fpm: 
    container_name: php-fpm
    command: php-fpm --allow-to-run-as-root
    image: torniker/phpfpm-5.6
    restart: always
    networks:
      - php_nginx_mysql
    volumes:
      - ./php-fpm/conf/fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php-fpm/conf/php.ini:/usr/local/etc/php/php.ini
      - ./nginx/www:/var/www
      - ./php-fpm/logs:/var/log/php-fpm
    privileged: true

  db:
    container_name: mysql
    image: mysql:5.6
    restart: always
    networks:
      - php_nginx_mysql
    volumes:
      - ./mysql/lib:/var/lib/mysql
      - ./mysql/conf:/etc/mysql
      - ./mysql/logs:/var/log/mysql
    ports:
      - "3306:3306"

networks:
  php_nginx_mysql:
    external: true
